# Generated by Django 3.1.7 on 2021-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime_mystery', 'Crime & Mystery'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci_fi', 'Science fiction'), ('thriller', 'Thriller'), ('western', 'Western')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
