# Generated by Django 3.1.7 on 2021-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210610_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
