# Generated by Django 3.1.7 on 2021-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210611_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
