# Generated by Django 3.1.7 on 2021-07-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_time',
        ),
    ]
